// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKa0gehx7nH744949ZZHGf72UpDL6CLts',
    appId: '1:989938081834:web:30c49f72f3d7be5378e353',
    messagingSenderId: '989938081834',
    projectId: 'soccer-score-dbdc4',
    authDomain: 'soccer-score-dbdc4.firebaseapp.com',
    storageBucket: 'soccer-score-dbdc4.firebasestorage.app',
    measurementId: 'G-Q747WV4DGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7CmQJhcwJTKa2sHk6Gsk4pJP3h7ABzhg',
    appId: '1:989938081834:android:d296dd2f31a12be178e353',
    messagingSenderId: '989938081834',
    projectId: 'soccer-score-dbdc4',
    storageBucket: 'soccer-score-dbdc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHPPNmfbjxyhQBLnXPXfMWgbnH72gWqFY',
    appId: '1:989938081834:ios:ef021a164539f20578e353',
    messagingSenderId: '989938081834',
    projectId: 'soccer-score-dbdc4',
    storageBucket: 'soccer-score-dbdc4.firebasestorage.app',
    iosBundleId: 'com.example.scheduledreminderProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHPPNmfbjxyhQBLnXPXfMWgbnH72gWqFY',
    appId: '1:989938081834:ios:ef021a164539f20578e353',
    messagingSenderId: '989938081834',
    projectId: 'soccer-score-dbdc4',
    storageBucket: 'soccer-score-dbdc4.firebasestorage.app',
    iosBundleId: 'com.example.scheduledreminderProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKa0gehx7nH744949ZZHGf72UpDL6CLts',
    appId: '1:989938081834:web:d496bab26372e50c78e353',
    messagingSenderId: '989938081834',
    projectId: 'soccer-score-dbdc4',
    authDomain: 'soccer-score-dbdc4.firebaseapp.com',
    storageBucket: 'soccer-score-dbdc4.firebasestorage.app',
    measurementId: 'G-MRSYDN4ZBV',
  );
}
